# Site settings
title: InSpace
url: "https://inspace4u.github.io/dllab"
baseurl: "/dllab"
motto: Insight In Space
email: inspace.co.kr
description: Insight In Space

# Build settings
markdown: kramdown

# post future
future: true

# pagination
paginate: 10