# Site settings
title: InSpace
url: "https://inspace4u.github.io/dllab"
baseurl: "/dllab"
motto: Your motto
email: inspace.co.kr
description: > # this means to ignore newlines until "baseurl:"
  Insight In Space
#twitter_username: jekyllrb
github_username:  inspace4u

# Build settings
markdown: kramdown

# post future
future: true